on:
  push:
    branches:
      - main

name: deploy website on push

jobs:

  web-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: get latest code
      uses: actions/checkout@v2

    - name: sync files locaweb
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.locaweb }}
        username: ${{ secrets.locaweb_user }}
        password: ${{ secrets.locaweb_pass }}
        server-dir: /var/www/public_html/
